---
# tasks file for master

- name: Setting Kubernetes repository
  yum_repository:
     name: kubernetes
     description: Kubernetes
     baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
     enabled: yes
     gpgcheck: yes
     repo_gpgcheck: yes
     gpgkey:
       - https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg  https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

- name: Installing softwares
  yum:
     name: "{{ item }}"
     state: present
  loop: "{{ packages }}"

- name: Starting Services
  service:
     name: "{{ item }}"
     state: started
     enabled: yes
  loop: "{{ services }}"

- name: Docker daemon.json file
  copy:
      dest: /etc/docker/daemon.json
      content: "{{ doc_daemon }}"

- name: Restart docker services
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Kubeadm image pull
  command: "kubeadm config images pull"
  changed_when: False

- name: nf call iptables.
  shell: echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  changed_when: False

- name: Kubeadm init
  command: "{{ kube_init }}"
  changed_when: False
  ignore_errors: True

- name: Creating .kube directory
  file:
    path: $HOME/.kube
    state: directory

- name: Copying kubernetes admin.conf file to $HOME/.kube/config
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    force: yes

- name: Changing owner permission
  shell: "chown $(id -u):$(id -g) $HOME/.kube/config"
  changed_when: False

- name: Applying flannel in Master Node
  command: "{{ kube_flannel }}"
  changed_when: False

- name: Generating token
  command: "kubeadm token create --print-join-command"
  register: token
  changed_when: False

- name: Creating facts directory in Master Node
  file:
      path: /etc/ansible/facts.d
      state: directory

- name: Creating fact file
  template:
      src: master_token.fact.j2
      dest: "/etc/ansible/facts.d/master_token.fact"

#Fetching the fact file from master to the localhost
- name: Fetch fact file from master to local
  fetch:
      dest: "{{ fetch_dest_dir }}"
      src: /etc/ansible/facts.d/master_token.fact
      flat: yes
  ignore_errors: True
